### ISSUE TITLE
Looks promising but can't get it to run

### ISSUE THREAD

**Issue by HuckFinnDiesel** [markus-leben/AutoAggie#1]
Not sure if I missed something, but when running main.py I just receive the following endlessly:

> Current screen: beginning_state
> Current turn: 0
>     checking images/playbutton.png
>     checking images/collectrewards.png
> Current screen: beginning_state
> Current turn: 0
>     checking images/playbutton.png
>     checking images/collectrewards.png
> Current screen: beginning_state
> Current turn: 0
>     checking images/playbutton.png
>     checking images/collectrewards.png

**Comment by markus-leben** [comment]
This error means its checking for the opening screen of snap and never seeing it. Most likely because the paybutton.png in images isn't sized to the dimensions of your instance of marvel snap. 

Just updated with a readme, requirements.txt, and settings.json. The rough instructions are in the readme, but the current solution is pretty hacky in that you'll have to manually screencap your buttons on Marvel Snap in order to get it to run correctly. Any suggestions on editing this for programmatically screencapping buttons would be welcome.
